# Generated by Django 4.0.6 on 2022-08-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_user_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
    ]
